openapi: 3.0.3

info:
  title: 工芸品管理システムAPI
  version: 1.0.1
  description: |
    **Change Log** 
    | ver. | 日付 | 変更者 | 変更箇所 | 変更内容 |
    | :-: | :-: | :-: | :-: | :-: |
    | 1.0.0 | 2023/07/29 | Zhong.Houji | - | 初版作成 |
    | 1.0.1 | 2023/10/02 | Zhong.Houji | ALL | DBに合わせて修正 |
    |  |  |  | Users-005 | 新規API追加 |
    |  |  |  | Users-007 | 新規API追加 |

    **Servers**  
    | 環境 | Url |
    | :- | :- |
    | local | http://localhost:3000/api |
    | dev | http://sample.com/api |

servers:
  - url: http://localhost:3000/api
    description: ローカル環境
  - url: http://sample.com/api
    description: 本番環境

tags:
  - name: Users
    description: ユーザーに関する操作
  - name: Crafts
    description: 工芸品に関する操作

security:
  - ApiKey: []
    Cookie: []

paths:
  /users:
    post:
      summary: '[Users-001] ユーザー登録'
      tags: [ Users ]
      security:
        - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account
                - password
                - nickname
              properties:
                account:
                  $ref: "#/components/schemas/Account"
                password:
                  $ref: "#/components/schemas/Password"
                nickname:
                  $ref: "#/components/schemas/Nickname"
      responses:
        '201':
          description: Created Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

    put:
      summary: '[Users-002] パスワード変更'
      tags: [ Users ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account
                - password
                - new_password
              properties:
                account:
                  $ref: "#/components/schemas/Account"
                password:
                  $ref: "#/components/schemas/Password"
                new_password:
                  $ref: "#/components/schemas/Password"
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '404':
          $ref: "#/components/responses/404"
        '500':
          $ref: "#/components/responses/500"

  /users/login:
    post:
      summary: '[Users-003] ログイン'
      tags: [ Users ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account
                - password
              properties:
                account:
                  $ref: "#/components/schemas/Account"
                password:
                  $ref: "#/components/schemas/Password"
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Create cookie
                  cookie:
                    type: string
                    example: cookie value
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

  /users/{account}:
    get:
      summary: '[Users-004] アカウントでユーザー情報取得'
      tags: [ Users ]
      parameters:
        - name: account
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '404':
          $ref: "#/components/responses/404"
        '500':
          $ref: "#/components/responses/500"

  /users/:uid:
    get:
      summary: '[Users-005] UIDでユーザー情報取得'
      tags: [ Users ]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '404':
          $ref: "#/components/responses/404"
        '500':
          $ref: "#/components/responses/500"

    delete:
      summary: '[Users-006] ユーザー削除'
      tags: [ Users ]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account
                - password
              properties:
                account:
                  $ref: "#/components/schemas/Account"
                password:
                  $ref: "#/components/schemas/Password"
      responses:
        '204':
          $ref: "#/components/responses/204"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '404':
          $ref: "#/components/responses/404"
        '500':
          $ref: "#/components/responses/500"

  /users/name:
    put:
      summary: '[Users-007] ニックネーム変更'
      tags: [ Users ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - new_nickname
              properties:
                new_nickname:
                  $ref: "#/components/schemas/Nickname"
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

  /crafts:
    post:
      summary: '[Crafts-001] 工芸品登録'
      description: 工芸品名称が重複された場合は上書き保存になる
      tags: [ Crafts ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  $ref: "#/components/schemas/Craft_name"
                region:
                  $ref: "#/components/schemas/Region"
                url:
                  $ref: "#/components/schemas/Url"
                japanese_name:
                  $ref: "#/components/schemas/Craft_japanese_name"
                category:
                  $ref: "#/components/schemas/Category"
                material:
                  $ref: "#/components/schemas/Material"
                atmosphere:
                  $ref: "#/components/schemas/Atmosphere"
                manufacturing:
                  $ref: "#/components/schemas/Manufacturing"
                era:
                  $ref: "#/components/schemas/Era"
                description:
                  $ref: "#/components/schemas/DescriptionText"
      responses:
        '201':
          description: Created Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Craft"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

  /crafts/:cid:
    get:
      summary: '[Crafts-002] 工芸品詳細取得'
      description: 工芸品IDによる工芸品詳細情報を取得
      tags: [ Crafts ]
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Craft"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '404':
          $ref: "#/components/responses/404"
        '500':
          $ref: "#/components/responses/500"

  /crafts/{name}:
    get:
      summary: '[Crafts-003] 名称で工芸品検索'
      description: 名称による工芸品基本情報を取得
      tags: [ Crafts ]
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Craft"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '404':
          $ref: "#/components/responses/404"
        '500':
          $ref: "#/components/responses/500"

  /crafts/{region}:
    get:
      summary: '[Crafts-004] 地域で工芸品検索'
      description: 地域による工芸品基本情報を取得
      tags: [ Crafts ]
      parameters:
        - name: region
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Craft"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

  /crafts/{era}:
    get:
      summary: '[Crafts-005] 年代で工芸品検索'
      description: 年代による工芸品基本情報を取得
      tags: [ Crafts ]
      parameters:
        - name: era
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Craft"
        '400':
          $ref: "#/components/responses/400"
        '403':
          $ref: "#/components/responses/403"
        '500':
          $ref: "#/components/responses/500"

components:
  securitySchemes:
    ApiKey:
      description: "API key authorization"
      type: apiKey
      in: header
      name: X-Api-Key
    Cookie:
      description: "Cookie authorization"
      type: apiKey
      in: cookie
      name: Cookie

  responses:
    '201':
      description: Create Success
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Create Success
    '204':
      description: Delete Success
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Delete Success
    '400':
      description: 400 Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Bad Request
    '403':
      description: 403 Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Forbidden
    '404':
      description: 404 Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not Found
    '500':
      description: 500 Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal Server Error

  schemas:
    Uid:
      description: ユーザーID
      type: integer
      example: 1
    Account:
      description: ログインアカウント
      type: string
      example: zhuzhu.ac
    Password: 
      description: パスワード
      type: string
      example: password
    Nickname:
      description: ニックネーム
      type: string
      example: ZhuZhu
    Created_at:
      description: 作成時刻 (UTC)
      type: string
      format: date-time
      example: 2023-10-01T14:30:40Z
    Updated_at:
      description: 更新時刻 (UTC)
      type: string
      format: date-time
      example: 2023-10-01T15:40:50Z
    User:
      type: object
      required:
        - uid
        - account
        - password
        - nickname
        - created_at
        - updated_at
      properties:
        uid:
          $ref: "#/components/schemas/Uid"
        account:
          $ref: "#/components/schemas/Account"
        nickname:
          $ref: "#/components/schemas/Nickname"
        created_at:
          $ref: "#/components/schemas/Created_at"
        updated_at:
          $ref: "#/components/schemas/Updated_at"

    Cid:
      description: 工芸品ID
      type: integer
      example: 1
    Craft_name:
      description: 工芸品名称
      type: string
      example: TBD
    Craft_japanese_name:
      description: 工芸品の日本語名称
      type: string
      example: TBD
    Region:
      description: 工芸品地域
      type: string
      example: TBD
    Url:
      description: 工芸品紹介URL
      type: string
      example: TBD
    Category:
      description: 工芸品カテゴリー
      type: string
      example: TBD
    Material:
      description: 工芸品材質
      type: string
      example: TBD
    Atmosphere:
      description: 工芸品雰囲気
      type: string
      example: TBD
    Manufacturing:
      description: 工芸品製造プロセス
      type: string
      example: TBD
    Era:
      description: 工芸品年代
      type: string
      example: TBD
    DescriptionText:
      description: 工芸品説明文
      type: string
      example: TBD
    Craft:
      type: object
      required:
        - cid
        - name
      properties:
        cid:
          $ref: "#/components/schemas/Cid"
        name:
          $ref: "#/components/schemas/Craft_name"
        region:
          $ref: "#/components/schemas/Region"
        url:
          $ref: "#/components/schemas/Url"
        japanese_name:
          $ref: "#/components/schemas/Craft_japanese_name"
        category:
          $ref: "#/components/schemas/Category"
        material:
          $ref: "#/components/schemas/Material"
        atmosphere:
          $ref: "#/components/schemas/Atmosphere"
        manufacturing:
          $ref: "#/components/schemas/Manufacturing"
        era:
          $ref: "#/components/schemas/Era"
        description:
          $ref: "#/components/schemas/DescriptionText"